### ISSUE TITLE
Some issues...

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [saulmm/CoordinatorBehaviorExample#2]
1. Importing via git (directly via Android-Studio) caused this issue to appear:

![untitled20150823230325](https://cloud.githubusercontent.com/assets/5357526/9429971/bdd26d22-49eb-11e5-8368-f936d5978a1e.png)

2. scrolling up too much causes a crash:

   java.lang.NullPointerException: Attempt to invoke virtual method 'float android.view.MotionEvent.getX()' on a null object reference
            at android.view.View.onTouchEvent(View.java:10316)
            at android.support.design.widget.CoordinatorLayout.onTouchEvent(CoordinatorLayout.java:449)
            at android.view.View.dispatchTouchEvent(View.java:8968)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2698)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2410)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2371)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2371)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2371)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2371)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2371)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2371)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2568)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1776)
            at android.app.Activity.dispatchTouchEvent(Activity.java:2866)
            at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
            at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2529)
            at android.view.View.dispatchPointerEvent(View.java:9173)
            at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4706)
            at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4544)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4068)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4121)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4087)
            at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4201)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4095)
            at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4258)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4068)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4121)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4087)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4095)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4068)
            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6564)
            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6454)
            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6425)
            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6654)
            at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
            at android.os.MessageQueue.nativePollOnce(Native Method)
            at android.os.MessageQueue.next(MessageQueue.java:143)
            at android.os.Looper.loop(Looper.java:130)
            at android.app.ActivityThread.main(ActivityThread.java:5942)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

3. scrolling is very weird and "jumpy", and I can cause it to show weird things, like having the circular image above the title (really outside of it, not even touching it).

**Comment by wingsum93** [comment]
i test this project and build in on my android 5.0 phone and is run and not crush.
also, i have no problem so far after i build the project.

(using github for window to download this project, and open using android studio but **use default gradle wrapper**  )

maybe you test again???

**Comment by saulmm** [comment]
Thanks @wingsum93, his instructions should do the trick. I have no problem cloning the repo and importing it on android studio.

Thanks!

**Comment by AndroidDeveloperLB** [comment]
it still fails by clone&import directly from Android Studio. Maybe they have a bug. 
I had to open the project again because of this. It works, but requires extra steps
